### PR TITLE
Adds docker_entrypoint variable

### PR DESCRIPTION
**Pull request by sjaakiejj**
Added a docker_entrypoint variable to override the entrypoint in the container. This allows starting containers with different commands in different environments.

### CODE REVIEW

**Comment by npalm** [comment]
@mpas @JeroenKnoops requires also the private load balancer module

**Comment by npalm** [comment]
@sjaakiejj You change looks all goed, but those extra properties doesn't look new to me. So just wondering did we used them in the past?

**Comment by JeroenKnoops** [comment]
@sjaakiejj and @npalm , is this still a relevant issue?

**Comment by npalm** [comment]
Sorry @sjaakiejj no activity for a long time, so I remove the PR

**Pull request closed without merging**
